CREATE TABLE PARTIDA_PONG (
    ID_PARTIDA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA      TIMESTAMP DEFAULT SYSTIMESTAMP,
    JUGADOR_1  VARCHAR2(50),
    JUGADOR_2  VARCHAR2(50),
    PUNTAJE_1  NUMBER,
    PUNTAJE_2  NUMBER,
    GANADOR    VARCHAR2(50)
);

COMMIT;